modLoader="javafml"
loaderVersion="[36,)"
license="Public Domain"

[[mods]]
modId="dogblockmod"
version="1.0.5"
displayName="the dog block mod"
credits="my name is mathias and im 21 year old lol, you can check my website to know a little more about me ;)"
displayURL="https://mathias777.com"
logoFile="logo.png"
authors="mathias777"
description='''
this mod will add dog blocs in your world and much more 
'''

[[dependencies.dogblockmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




