modLoader="javafml"
loaderVersion="[36,)"
license="Public Domain"

[[mods]]
modId="dogblockmod"
version="1.1"
displayName="the dog block mod"
credits="my name is vaden and im 23 year old lol, you can check my website to know a little more about me ;)"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dog-blocks"
authors="vsilet"
description='''
this mod will add dog blocs in your world and much more 
'''

[[dependencies.dogblockmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




