
package net.useless.dogblockmod.world.biome;

import net.useless.dogblockmod.entity.Par97Entity;
import net.useless.dogblockmod.entity.Par96Entity;
import net.useless.dogblockmod.entity.Par95Entity;
import net.useless.dogblockmod.entity.Par94Entity;
import net.useless.dogblockmod.entity.Par93Entity;
import net.useless.dogblockmod.entity.Par92Entity;
import net.useless.dogblockmod.entity.Par91Entity;
import net.useless.dogblockmod.entity.Par87Entity;
import net.useless.dogblockmod.entity.Par86Entity;
import net.useless.dogblockmod.entity.Par85Entity;
import net.useless.dogblockmod.entity.Par84Entity;
import net.useless.dogblockmod.entity.Par83Entity;
import net.useless.dogblockmod.entity.Par82Entity;
import net.useless.dogblockmod.entity.Par81Entity;
import net.useless.dogblockmod.entity.Par77Entity;
import net.useless.dogblockmod.entity.Par76Entity;
import net.useless.dogblockmod.entity.Par75Entity;
import net.useless.dogblockmod.entity.Par74Entity;
import net.useless.dogblockmod.entity.Par73Entity;
import net.useless.dogblockmod.entity.Par72Entity;
import net.useless.dogblockmod.entity.Par71Entity;
import net.useless.dogblockmod.entity.Par57Entity;
import net.useless.dogblockmod.entity.Par56Entity;
import net.useless.dogblockmod.entity.Par55Entity;
import net.useless.dogblockmod.entity.Par54Entity;
import net.useless.dogblockmod.entity.Par53Entity;
import net.useless.dogblockmod.entity.Par52Entity;
import net.useless.dogblockmod.entity.Par51Entity;
import net.useless.dogblockmod.entity.Par47Entity;
import net.useless.dogblockmod.entity.Par46Entity;
import net.useless.dogblockmod.entity.Par45Entity;
import net.useless.dogblockmod.entity.Par44Entity;
import net.useless.dogblockmod.entity.Par43Entity;
import net.useless.dogblockmod.entity.Par42Entity;
import net.useless.dogblockmod.entity.Par41Entity;
import net.useless.dogblockmod.entity.Par37Entity;
import net.useless.dogblockmod.entity.Par36Entity;
import net.useless.dogblockmod.entity.Par35Entity;
import net.useless.dogblockmod.entity.Par34Entity;
import net.useless.dogblockmod.entity.Par347Entity;
import net.useless.dogblockmod.entity.Par346Entity;
import net.useless.dogblockmod.entity.Par345Entity;
import net.useless.dogblockmod.entity.Par344Entity;
import net.useless.dogblockmod.entity.Par343Entity;
import net.useless.dogblockmod.entity.Par342Entity;
import net.useless.dogblockmod.entity.Par341Entity;
import net.useless.dogblockmod.entity.Par33Entity;
import net.useless.dogblockmod.entity.Par337Entity;
import net.useless.dogblockmod.entity.Par336Entity;
import net.useless.dogblockmod.entity.Par335Entity;
import net.useless.dogblockmod.entity.Par334Entity;
import net.useless.dogblockmod.entity.Par333Entity;
import net.useless.dogblockmod.entity.Par332Entity;
import net.useless.dogblockmod.entity.Par331Entity;
import net.useless.dogblockmod.entity.Par32Entity;
import net.useless.dogblockmod.entity.Par327Entity;
import net.useless.dogblockmod.entity.Par326Entity;
import net.useless.dogblockmod.entity.Par325Entity;
import net.useless.dogblockmod.entity.Par324Entity;
import net.useless.dogblockmod.entity.Par323Entity;
import net.useless.dogblockmod.entity.Par322Entity;
import net.useless.dogblockmod.entity.Par321Entity;
import net.useless.dogblockmod.entity.Par31Entity;
import net.useless.dogblockmod.entity.Par317Entity;
import net.useless.dogblockmod.entity.Par316Entity;
import net.useless.dogblockmod.entity.Par315Entity;
import net.useless.dogblockmod.entity.Par314Entity;
import net.useless.dogblockmod.entity.Par313Entity;
import net.useless.dogblockmod.entity.Par312Entity;
import net.useless.dogblockmod.entity.Par311Entity;
import net.useless.dogblockmod.entity.Par307Entity;
import net.useless.dogblockmod.entity.Par306Entity;
import net.useless.dogblockmod.entity.Par305Entity;
import net.useless.dogblockmod.entity.Par304Entity;
import net.useless.dogblockmod.entity.Par303Entity;
import net.useless.dogblockmod.entity.Par302Entity;
import net.useless.dogblockmod.entity.Par301Entity;
import net.useless.dogblockmod.entity.Par297Entity;
import net.useless.dogblockmod.entity.Par296Entity;
import net.useless.dogblockmod.entity.Par295Entity;
import net.useless.dogblockmod.entity.Par294Entity;
import net.useless.dogblockmod.entity.Par293Entity;
import net.useless.dogblockmod.entity.Par292Entity;
import net.useless.dogblockmod.entity.Par291Entity;
import net.useless.dogblockmod.entity.Par27Entity;
import net.useless.dogblockmod.entity.Par277Entity;
import net.useless.dogblockmod.entity.Par276Entity;
import net.useless.dogblockmod.entity.Par275Entity;
import net.useless.dogblockmod.entity.Par274Entity;
import net.useless.dogblockmod.entity.Par273Entity;
import net.useless.dogblockmod.entity.Par272Entity;
import net.useless.dogblockmod.entity.Par271Entity;
import net.useless.dogblockmod.entity.Par26Entity;
import net.useless.dogblockmod.entity.Par267Entity;
import net.useless.dogblockmod.entity.Par266Entity;
import net.useless.dogblockmod.entity.Par265Entity;
import net.useless.dogblockmod.entity.Par264Entity;
import net.useless.dogblockmod.entity.Par263Entity;
import net.useless.dogblockmod.entity.Par262Entity;
import net.useless.dogblockmod.entity.Par261Entity;
import net.useless.dogblockmod.entity.Par25Entity;
import net.useless.dogblockmod.entity.Par257Entity;
import net.useless.dogblockmod.entity.Par256Entity;
import net.useless.dogblockmod.entity.Par255Entity;
import net.useless.dogblockmod.entity.Par254Entity;
import net.useless.dogblockmod.entity.Par253Entity;
import net.useless.dogblockmod.entity.Par252Entity;
import net.useless.dogblockmod.entity.Par251Entity;
import net.useless.dogblockmod.entity.Par24Entity;
import net.useless.dogblockmod.entity.Par247Entity;
import net.useless.dogblockmod.entity.Par246Entity;
import net.useless.dogblockmod.entity.Par245Entity;
import net.useless.dogblockmod.entity.Par244Entity;
import net.useless.dogblockmod.entity.Par243Entity;
import net.useless.dogblockmod.entity.Par242Entity;
import net.useless.dogblockmod.entity.Par241Entity;
import net.useless.dogblockmod.entity.Par23Entity;
import net.useless.dogblockmod.entity.Par237Entity;
import net.useless.dogblockmod.entity.Par236Entity;
import net.useless.dogblockmod.entity.Par235Entity;
import net.useless.dogblockmod.entity.Par234Entity;
import net.useless.dogblockmod.entity.Par233Entity;
import net.useless.dogblockmod.entity.Par232Entity;
import net.useless.dogblockmod.entity.Par231Entity;
import net.useless.dogblockmod.entity.Par22Entity;
import net.useless.dogblockmod.entity.Par227Entity;
import net.useless.dogblockmod.entity.Par226Entity;
import net.useless.dogblockmod.entity.Par225Entity;
import net.useless.dogblockmod.entity.Par224Entity;
import net.useless.dogblockmod.entity.Par223Entity;
import net.useless.dogblockmod.entity.Par222Entity;
import net.useless.dogblockmod.entity.Par221Entity;
import net.useless.dogblockmod.entity.Par21Entity;
import net.useless.dogblockmod.entity.Par217Entity;
import net.useless.dogblockmod.entity.Par216Entity;
import net.useless.dogblockmod.entity.Par215Entity;
import net.useless.dogblockmod.entity.Par214Entity;
import net.useless.dogblockmod.entity.Par213Entity;
import net.useless.dogblockmod.entity.Par212Entity;
import net.useless.dogblockmod.entity.Par211Entity;
import net.useless.dogblockmod.entity.Par207Entity;
import net.useless.dogblockmod.entity.Par206Entity;
import net.useless.dogblockmod.entity.Par205Entity;
import net.useless.dogblockmod.entity.Par204Entity;
import net.useless.dogblockmod.entity.Par203Entity;
import net.useless.dogblockmod.entity.Par202Entity;
import net.useless.dogblockmod.entity.Par201Entity;
import net.useless.dogblockmod.entity.Par197Entity;
import net.useless.dogblockmod.entity.Par196Entity;
import net.useless.dogblockmod.entity.Par195Entity;
import net.useless.dogblockmod.entity.Par194Entity;
import net.useless.dogblockmod.entity.Par193Entity;
import net.useless.dogblockmod.entity.Par192Entity;
import net.useless.dogblockmod.entity.Par191Entity;
import net.useless.dogblockmod.entity.Par187Entity;
import net.useless.dogblockmod.entity.Par186Entity;
import net.useless.dogblockmod.entity.Par185Entity;
import net.useless.dogblockmod.entity.Par184Entity;
import net.useless.dogblockmod.entity.Par183Entity;
import net.useless.dogblockmod.entity.Par182Entity;
import net.useless.dogblockmod.entity.Par181Entity;
import net.useless.dogblockmod.entity.Par17Entity;
import net.useless.dogblockmod.entity.Par177Entity;
import net.useless.dogblockmod.entity.Par176Entity;
import net.useless.dogblockmod.entity.Par175Entity;
import net.useless.dogblockmod.entity.Par174Entity;
import net.useless.dogblockmod.entity.Par173Entity;
import net.useless.dogblockmod.entity.Par172Entity;
import net.useless.dogblockmod.entity.Par171Entity;
import net.useless.dogblockmod.entity.Par16Entity;
import net.useless.dogblockmod.entity.Par167Entity;
import net.useless.dogblockmod.entity.Par166Entity;
import net.useless.dogblockmod.entity.Par165Entity;
import net.useless.dogblockmod.entity.Par164Entity;
import net.useless.dogblockmod.entity.Par163Entity;
import net.useless.dogblockmod.entity.Par162Entity;
import net.useless.dogblockmod.entity.Par161Entity;
import net.useless.dogblockmod.entity.Par15Entity;
import net.useless.dogblockmod.entity.Par157Entity;
import net.useless.dogblockmod.entity.Par156Entity;
import net.useless.dogblockmod.entity.Par155Entity;
import net.useless.dogblockmod.entity.Par154Entity;
import net.useless.dogblockmod.entity.Par153Entity;
import net.useless.dogblockmod.entity.Par152Entity;
import net.useless.dogblockmod.entity.Par151Entity;
import net.useless.dogblockmod.entity.Par14Entity;
import net.useless.dogblockmod.entity.Par147Entity;
import net.useless.dogblockmod.entity.Par146Entity;
import net.useless.dogblockmod.entity.Par145Entity;
import net.useless.dogblockmod.entity.Par144Entity;
import net.useless.dogblockmod.entity.Par143Entity;
import net.useless.dogblockmod.entity.Par142Entity;
import net.useless.dogblockmod.entity.Par141Entity;
import net.useless.dogblockmod.entity.Par13Entity;
import net.useless.dogblockmod.entity.Par137Entity;
import net.useless.dogblockmod.entity.Par136Entity;
import net.useless.dogblockmod.entity.Par135Entity;
import net.useless.dogblockmod.entity.Par134Entity;
import net.useless.dogblockmod.entity.Par133Entity;
import net.useless.dogblockmod.entity.Par132Entity;
import net.useless.dogblockmod.entity.Par131Entity;
import net.useless.dogblockmod.entity.Par12Entity;
import net.useless.dogblockmod.entity.Par127Entity;
import net.useless.dogblockmod.entity.Par126Entity;
import net.useless.dogblockmod.entity.Par125Entity;
import net.useless.dogblockmod.entity.Par124Entity;
import net.useless.dogblockmod.entity.Par123Entity;
import net.useless.dogblockmod.entity.Par122Entity;
import net.useless.dogblockmod.entity.Par121Entity;
import net.useless.dogblockmod.entity.Par11Entity;
import net.useless.dogblockmod.entity.Par117Entity;
import net.useless.dogblockmod.entity.Par116Entity;
import net.useless.dogblockmod.entity.Par115Entity;
import net.useless.dogblockmod.entity.Par114Entity;
import net.useless.dogblockmod.entity.Par113Entity;
import net.useless.dogblockmod.entity.Par112Entity;
import net.useless.dogblockmod.entity.Par111Entity;
import net.useless.dogblockmod.entity.Par107Entity;
import net.useless.dogblockmod.entity.Par106Entity;
import net.useless.dogblockmod.entity.Par105Entity;
import net.useless.dogblockmod.entity.Par104Entity;
import net.useless.dogblockmod.entity.Par103Entity;
import net.useless.dogblockmod.entity.Par102Entity;
import net.useless.dogblockmod.entity.Par101Entity;
import net.useless.dogblockmod.block.ParasitegrassBlock;
import net.useless.dogblockmod.block.ParasitedirtBlock;
import net.useless.dogblockmod.DogblockmodModElements;

import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.BiomeManager;

import net.minecraft.world.gen.surfacebuilders.SurfaceBuilderConfig;
import net.minecraft.world.gen.surfacebuilders.SurfaceBuilder;
import net.minecraft.world.gen.feature.structure.StructureFeatures;
import net.minecraft.world.biome.MobSpawnInfo;
import net.minecraft.world.biome.DefaultBiomeFeatures;
import net.minecraft.world.biome.BiomeGenerationSettings;
import net.minecraft.world.biome.BiomeAmbience;
import net.minecraft.world.biome.Biome;
import net.minecraft.util.registry.WorldGenRegistries;
import net.minecraft.util.registry.Registry;
import net.minecraft.util.RegistryKey;
import net.minecraft.entity.EntityClassification;

@DogblockmodModElements.ModElement.Tag
public class ParasitebiomeBiome extends DogblockmodModElements.ModElement {
	public static Biome biome;

	public ParasitebiomeBiome(DogblockmodModElements instance) {
		super(instance, 1680);
		FMLJavaModLoadingContext.get().getModEventBus().register(new BiomeRegisterHandler());
	}

	private static class BiomeRegisterHandler {
		@SubscribeEvent
		public void registerBiomes(RegistryEvent.Register<Biome> event) {
			if (biome == null) {
				BiomeAmbience effects = new BiomeAmbience.Builder().setFogColor(-10092442).setWaterColor(-10092442).setWaterFogColor(-10092442)
						.withSkyColor(-10092442).withFoliageColor(-10092442).withGrassColor(-10092442).build();
				BiomeGenerationSettings.Builder biomeGenerationSettings = new BiomeGenerationSettings.Builder()
						.withSurfaceBuilder(SurfaceBuilder.DEFAULT.func_242929_a(new SurfaceBuilderConfig(ParasitegrassBlock.block.getDefaultState(),
								ParasitedirtBlock.block.getDefaultState(), ParasitedirtBlock.block.getDefaultState())));
				biomeGenerationSettings.withStructure(StructureFeatures.STRONGHOLD);
				biomeGenerationSettings.withStructure(StructureFeatures.MINESHAFT);
				biomeGenerationSettings.withStructure(StructureFeatures.MINESHAFT_BADLANDS);
				biomeGenerationSettings.withStructure(StructureFeatures.VILLAGE_PLAINS);
				biomeGenerationSettings.withStructure(StructureFeatures.MANSION);
				biomeGenerationSettings.withStructure(StructureFeatures.DESERT_PYRAMID);
				biomeGenerationSettings.withStructure(StructureFeatures.BURIED_TREASURE);
				DefaultBiomeFeatures.withCavesAndCanyons(biomeGenerationSettings);
				DefaultBiomeFeatures.withOverworldOres(biomeGenerationSettings);
				DefaultBiomeFeatures.withFrozenTopLayer(biomeGenerationSettings);
				DefaultBiomeFeatures.withEmeraldOre(biomeGenerationSettings);
				DefaultBiomeFeatures.withExtraGoldOre(biomeGenerationSettings);
				MobSpawnInfo.Builder mobSpawnInfo = new MobSpawnInfo.Builder().isValidSpawnBiomeForPlayer();
				mobSpawnInfo.withSpawner(EntityClassification.CREATURE, new MobSpawnInfo.Spawners(Par101Entity.entity, 20, 1, 5));
				mobSpawnInfo.withSpawner(EntityClassification.CREATURE, new MobSpawnInfo.Spawners(Par102Entity.entity, 20, 1, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par103Entity.entity, 20, 1, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par104Entity.entity, 20, 1, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par105Entity.entity, 20, 1, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par106Entity.entity, 20, 1, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par107Entity.entity, 20, 1, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par111Entity.entity, 20, 1, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par112Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par113Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par114Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par115Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par116Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par117Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par121Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par122Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par123Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par124Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par125Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par126Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par127Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par11Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par12Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par13Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par14Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par15Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par16Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par17Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par21Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par22Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par23Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par24Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par25Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par26Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par27Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par31Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par32Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par33Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par34Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par35Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par36Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par37Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par41Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par42Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par43Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par44Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par45Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par46Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par47Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par51Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par52Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par53Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par54Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par55Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par56Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par57Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par71Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par72Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par73Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par74Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par75Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par76Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par77Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par81Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par82Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par83Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par84Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par85Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par86Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par87Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par91Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par92Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par93Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par94Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par95Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par96Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par97Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par131Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par132Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par133Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par134Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par135Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par136Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par137Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par141Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par142Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par143Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par144Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par145Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par146Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par147Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par151Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par152Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par153Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par154Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par155Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par156Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par157Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par161Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par162Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par163Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par164Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par165Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par166Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par167Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par171Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par172Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par173Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par174Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par175Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par176Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par177Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par181Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par182Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par183Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par184Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par185Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par186Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par187Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par191Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par192Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par193Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par194Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par195Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par196Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par197Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par201Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par202Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par203Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par204Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par205Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par206Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par207Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par211Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par212Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par213Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par214Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par215Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par216Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par217Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par221Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par222Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par223Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par224Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par225Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par226Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par227Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par231Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par232Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par233Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par234Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par235Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par236Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par237Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par241Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par242Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par243Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par244Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par245Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par246Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par247Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par251Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par252Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par253Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par254Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par255Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par256Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par257Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par261Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par262Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par263Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par264Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par265Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par266Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par267Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par271Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par272Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par273Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par274Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par275Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par276Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par277Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par291Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par292Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par293Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par294Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par295Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par296Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par297Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par301Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par302Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par303Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par304Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par305Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par306Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par307Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par311Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par312Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par313Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par314Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par315Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par316Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par317Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par321Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par322Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par323Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par324Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par325Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par326Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par327Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par331Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par332Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par333Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par334Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par335Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par336Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par337Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par341Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par342Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par343Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par344Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par345Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par346Entity.entity, 20, 4, 4));
				mobSpawnInfo.withSpawner(EntityClassification.MONSTER, new MobSpawnInfo.Spawners(Par347Entity.entity, 20, 4, 4));
				biome = new Biome.Builder().precipitation(Biome.RainType.NONE).category(Biome.Category.NONE).depth(0.3f).scale(0.5f).temperature(2f)
						.downfall(0f).setEffects(effects).withMobSpawnSettings(mobSpawnInfo.copy())
						.withGenerationSettings(biomeGenerationSettings.build()).build();
				event.getRegistry().register(biome.setRegistryName("dogblockmod:parasitebiome"));
			}
		}
	}

	@Override
	public void init(FMLCommonSetupEvent event) {
		BiomeManager.addBiome(BiomeManager.BiomeType.DESERT,
				new BiomeManager.BiomeEntry(RegistryKey.getOrCreateKey(Registry.BIOME_KEY, WorldGenRegistries.BIOME.getKey(biome)), 20));
	}
}
